# Generated by Django 5.0.6 on 2024-07-30 15:56

import django.db.models.deletion
import django.utils.timezone
import importwares.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignationNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignation_number', models.CharField(editable=False, max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PalletPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RackPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pallet_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rack_places', to='importwares.palletplace')),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='Add desc here')),
                ('ean', models.CharField(max_length=13, validators=[importwares.models.validate_ean])),
                ('pal_code', models.CharField(help_text="Pallet code must starts with 'P' and be 12 characters long.", max_length=12, null=True, validators=[importwares.models.validate_pal_code])),
                ('quantity', models.DecimalField(decimal_places=0, default=0, max_digits=6)),
                ('sku', models.CharField(default=importwares.models.generate_sku, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_buy_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sell_price', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('total_sell_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('unit_weight', models.DecimalField(decimal_places=2, default=None, max_digits=6)),
                ('total_weight', models.DecimalField(decimal_places=2, default=None, max_digits=6)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='importwares.category')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='importwares.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='WarehousePallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(default=importwares.models.generate_pid, editable=False, max_length=10, unique=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('u_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_weight', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo', to='importwares.cargo')),
            ],
        ),
        migrations.CreateModel(
            name='AssignedPallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_assigned', models.BooleanField(default=False)),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importwares.assignationnumber')),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importwares.warehousepallet')),
            ],
        ),
    ]
