# Generated by Django 5.0.6 on 2024-08-01 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importwares', '0002_remove_rackplace_pallet_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalletPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(max_length=4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RackPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_name', models.CharField(max_length=2, unique=True)),
                ('is_occupied', models.BooleanField(default=False)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importwares.palletplace')),
            ],
        ),
    ]
