# Generated by Django 5.0.6 on 2024-08-04 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importwares', '0003_palletplace_rackplace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rackplace',
            name='rack_name',
        ),
    ]
