# Generated by Django 5.0.6 on 2024-08-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importwares', '0004_remove_rackplace_rack_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rackplace',
            name='place',
        ),
        migrations.AddField(
            model_name='rackplace',
            name='rid',
            field=models.CharField(default='Add', max_length=4, unique=True),
        ),
        migrations.DeleteModel(
            name='PalletPlace',
        ),
    ]
